### PR TITLE
add IMGUI support

### LINKED ISSUE #10: ImGui Support
There are some Sokol examples to be ported that use ImGui.

Since only `build.zig` is available, zig-pkg will be used to download D packages.

https://github.com/kassane/sokol-d/blob/43d371b48e0a2ca951aa44234be8a9cbe9179e6b/build.zig.zon#L4-L10

### D binding
- https://github.com/BindBC/bindbc-imgui
- https://github.com/BindBC/bindbc-imgui/issues/2

# References
- https://github.com/floooh/sokol-zig/issues/29
- https://github.com/floooh/sokol-rust/issues/19
- https://github.com/floooh/sokol/blob/master/util/sokol_imgui.h

### PR DESCRIPTION
**Pull request by kassane**
fix #10 

old branch, need long rebase... I'll delete (for testing only)
https://github.com/kassane/sokol-d/tree/imgui-support

inspired by:
- https://github.com/floooh/sokol-zig/pull/69
- https://github.com/floooh/sokol-zig/pull/70

### CODE REVIEW

**Comment by kassane** [comment]
Need cimgui binding for run example. Old module amalgamation cimgui + sokol_imgui:
https://github.com/kassane/sokol-d/blob/1d1fc586969aba82fc6b854aeb2d16f7ec656976/src/sokol/imgui.d

now, only sokol_imgui:
https://github.com/kassane/sokol-d/blob/1110006dd280fca4be0a16402fc6455f1c82f494/src/examples/imgui.d#L103-L115

**Comment by kassane** [comment]
### Some questions (for zig-dev)

#### What would you add `cimgui` to the example?

Unlike `zig translate-c`, `importC` doesn't read header, only C source.
However, this still falls short (`translate-c` also has some issues). The only difference between the two projects is the level of support (zig project wins here).

<details>
<summary>More info - commands</summary>

Zig `translate-c` has the ability to convert all the code (declaration + implementation), `importC` just the declaration (equivalent to rust-bindgen or sokol_gen).

```bash
# zig
$ zig translate-c <c-flags> <C source> -lc
# D
$ ldmd2/ldc2 <C source> -Hf=<D interface source> (*.di)
# zig have inside clang,
# ldc2 need call cc (system compiler) - like rustc.
# But -gcc is used only C source and -linker= any object (w/o C source) 
# and rustc equivalence is -linker= flag.
```
</details>

And not have current D module about `cimgui`, only old `imgui` (C++, no `extern(C)`) version.

**Comment by kassane** [comment]
Please, @floooh.

Test it!

<details>
<summary>Preview</summary>

- Linux (native):
image

- Wasm32/Firefox:
image
</details>

**Note:**  For wasm32 build change...
https://github.com/kassane/sokol-d/blob/8d589cb82b9a509f561147e3feec853cc1663157/build.zig#L245

Why block? CI error. Why `imgui-cpp` need `assert.h`, but rebuild (no-clean global cache) works!

And for old ldc2 versions (1.36...1.38 [latest]) change... `.freestanding` to `.emscripten` or try ldc2-master
https://github.com/kassane/sokol-d/blob/8d589cb82b9a509f561147e3feec853cc1663157/build.zig#L512-L515

**Comment by kassane** [comment]
> Note that there was an bug in the translateC step in the cimgui sample which caused this above error about missing assert.h in imgui.h when trying to build for wasm32-emscripten. I fixed this by always running the translateC step with the host target [...]

According to this solution, perhaps it would have been possible to use **importC** to bypass the error, just like **translate-c**.
However, the `assert.h` error occurs during the **libsokol** build, a step before ldc2.
I know there exists a step wait for `emsdk_setup` in **libsokol** and this will run **imgui** in a direct dependency.

https://github.com/kassane/sokol-d/blob/20fe32c375502d2d4bc709086a0fdd2027e31f0c/build.zig#L79-L82
https://github.com/kassane/sokol-d/blob/20fe32c375502d2d4bc709086a0fdd2027e31f0c/build.zig#L184-L194

---

Another question that puzzles me. Would it be useful to use the `build.zig` dependency to make **sokol-zig** a dependency of **sokol-d**?
That way we could reduce the complexity redundancy of `build.zig`.

**Comment by kassane** [comment]
@floooh , my `assert.h` fix - if **with_imgui** enabled, move `lib.step.dependOn(&emsdk_setup.step);` to `libimgui.step.dependOn(&emsdk_setup.step);`
https://github.com/kassane/sokol-d/commit/bca71beb160425aeecf7a76f7256f4e2ca356744

**Comment by floooh** [comment]
Ah btw, I fixed this a bit differently, by letting the cimgui library depend on the sokol C library (up in the top level project):

https://github.com/floooh/sokol-zig-imgui-sample/blob/87d703e2f1f43135a5a5e9bfc2a56910d48b7e7b/build.zig#L69-L73

Since the sokol C library depends on the Emscripten SDK setup this also guarantees that the SDK is setup.

> Another question that puzzles me. Would it be useful to use the build.zig dependency to make sokol-zig a dependency of sokol-d?

Not a fan tbh, it would probably make more sense to move the emsdk setup into a separate project (and Zig package) which could then be used both by sokol-zig and sokol-d.

**Comment by floooh** [comment]
Wrote a ticket for that idea (to handle the C library stuff in sokol-zig build.zig): https://github.com/floooh/sokol-zig/issues/71

**Comment by kassane** [comment]
> it would probably make more sense to move the emsdk stuff into a separate project (and Zig package) which could then be used both by sokol-zig and sokol-d.

Make sense. Like,
https://github.com/kassane/anotherBuildStep (a.k.a **abs**)
Also, I have not yet completed emsdk support. But in **pacman.d**, besides **sokol-d** (passing libsokol + D modules), using abs to set *ldc2*.
Maybe *ldc2/ldmd2* could be ported outside of sokol-d using this idea.

**Pull request merged**
